app/accounts/urls.py
from accounts import views
from accounts.views import ProfileView

from django.urls import path

app_name = 'accounts'


urlpatterns = [
    path('signup/', views.UserSignUpView.as_view(), name='signup'),
    path('activate/<uuid:username>/', views.UserActivateView.as_view(), name='activate'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

app/api/urls.py
from api import views

from django.urls import path

from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from rest_framework import permissions
from rest_framework.routers import DefaultRouter

app_name = 'api'

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


router = DefaultRouter()
router.register('rates', views.RateViewSet,  basename='rate')
router.register('contactus', views.ContactUsViewSet,  basename='contactus')
router.register('sources', views.SourceViewSet, basename='source')

urlpatterns = [path('rates/latest/', views.LatestRatesView.as_view(), name='rates-latest')]

urlpatterns += router.urls

app/currency/urls.py
from currency.views import (
    ContactUsCreateView,
    ContactusListView,

    RateCreateView,
    RateDeleteView,
    RateDetailsView,
    RateListView,
    RateUpdateView,

    SourceCreateView,
    SourceDeleteView,
    SourceDetailsView,
    SourceListView,
    SourceUpdateView,
)

from django.urls import path

app_name = 'currency'


urlpatterns = (
    path('rate/list/', RateListView.as_view(), name='rate-list'),
    path('rate/create/', RateCreateView.as_view(), name='rate-create'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),
    path('rate/details/<int:pk>/', RateDetailsView.as_view(), name='rate-details'),

    path('contactus/list/', ContactusListView.as_view(), name='contactus-list'),
    path('contactus/create/', ContactUsCreateView.as_view(), name='contactus-create'),

    path('source/list/', SourceListView.as_view(), name='source-list'),
    path('source/create/', SourceCreateView.as_view(), name='source-create'),
    path('source/update/<int:pk>/', SourceUpdateView.as_view(), name='source-update'),
    path('source/delete/<int:pk>/', SourceDeleteView.as_view(), name='source-delete'),
    path('source/details/<int:pk>/', SourceDetailsView.as_view(), name='source-details'),
)

app/settings/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import (
    TemplateView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('django.contrib.auth.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
    path('silk/', include('silk.urls', namespace='silk')),

    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('currency/', include('currency.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/currency/models.py
from currency import model_choices as mch

from django.db import models
from django.templatetags.static import static


def avatar_upload_to(instance, filename):
    return f'avatars/{instance.id}/{filename}'


class Rate(models.Model):
    buy = models.DecimalField(max_digits=6, decimal_places=2)
    sale = models.DecimalField(max_digits=6, decimal_places=2)
    created = models.DateField(auto_now_add=True)
    type = models.PositiveSmallIntegerField(  # noqa: A003
        choices=mch.RateTypeChoices.choices,
        default=mch.RateTypeChoices.USD,
    )
    source = models.ForeignKey('currency.Source', on_delete=models.CASCADE)


class ContactUs(models.Model):
    class Meta:
        verbose_name = 'Contact Us'
        verbose_name_plural = 'Contact Us'

    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=128)
    reply_to = models.EmailField()
    subject = models.CharField(max_length=128)
    body = models.CharField(max_length=1024)
    raw_content = models.TextField()


class Source(models.Model):
    source_url = models.CharField(max_length=255)
    name = models.CharField(max_length=64)
    created = models.DateTimeField(auto_now_add=True)
    avatar = models.FileField(
        upload_to=avatar_upload_to,
        default=None,
        null=True,
        blank=True,
    )
    code_name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name

    @property
    def avatar_url(self):
        if self.avatar:
            return self.avatar.url
        return static('images/default-avatar.jpg')


class RequestResponseLog(models.Model):
    path = models.CharField(max_length=255)
    request_method = models.CharField(max_length=255)
    time = models.DecimalField(max_digits=6, decimal_places=4)

# def save(self, *args, **kwargs):
#     if not self.created:
#         self.created = datetime.now()
#     return super().save(*args, **kwargs)

app/currency/forms.py
from currency.models import Rate, Source

from django import forms


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = {
            'buy',
            'sale',
            'type',
            'source',
        }


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = {
            'source_url',
            'name',
        }

app/currency/views.py
from currency.filters import RateFilter
from currency.forms import RateForm, SourceForm
from currency.models import ContactUs, Rate, Source
from currency.tasks import send_email_in_background

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from django_filters.views import FilterView


class RateListView(FilterView):
    paginate_by = 10
    queryset = Rate.objects.all().order_by('-created').select_related('source')
    filterset_class = RateFilter

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['pagination_filter'] = "&".join(
            f"{key}={value}"
            for key, value in self.request.GET.items()
            if key != 'page'
        )
        return context


class RateCreateView(CreateView):
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'currency/rate_create.html'


class RateUpdateView(UserPassesTestMixin, UpdateView):
    form_class = RateForm
    model = Rate
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'currency/rate_update.html'

    def test_func(self):
        return self.request.user.is_superuser


class RateDetailsView(LoginRequiredMixin, DetailView):
    model = Rate


class RateDeleteView(UserPassesTestMixin, DeleteView):
    model = Rate
    template_name = 'currency/rate_delete.html'
    success_url = reverse_lazy('currency:rate-list')

    def test_func(self):
        return self.request.user.is_superuser


class ContactusListView(ListView):
    queryset = ContactUs.objects.all()


class ContactUsCreateView(CreateView):
    model = ContactUs
    template_name = 'currency/contactus_create.html'
    success_url = reverse_lazy('index')
    fields = (
        'name',
        'reply_to',
        'subject',
        'body',
    )

    def form_valid(self, form):
        redirect = super().form_valid(form)
        subject = 'User ContactUs'
        body = f'''
            Request From: {self.object.name}
            Email to reply: {self.object.reply_to}
            Subject: {self.object.subject}
            Body: {self.object.body}
        '''
        send_email_in_background.delay(subject, body)
        # send_email_in_background.apply_async(args=(subject, body))
        '''
        00-8.59 | 9.00-19.00 | 19.01 - 23.59
        9.00    |    send    | 9.00 next day
        '''
        # from datetime import datetime, timedelta
        # eta = datetime(2021, 11, 21, 19, 00, 00)
        # send_email_in_background.apply_async(
        #     kwargs={'subject': subject, 'body': body},
        #     countdown=120,
        # eta=eta,
        # )
        return redirect


class SourceListView(ListView):
    queryset = Source.objects.all().order_by('-created')


class SourceCreateView(CreateView):
    form_class = SourceForm
    success_url = reverse_lazy('currency:source-list')
    template_name = 'currency/source_create.html'


class SourceUpdateView(UpdateView):
    form_class = SourceForm
    model = Source
    success_url = reverse_lazy('currency:source-list')
    template_name = 'currency/source_update.html'


class SourceDetailsView(UpdateView):
    model = Source
    template_name = 'currency/source_detail.html'
    success_url = reverse_lazy('currency:source-list')
    fields = (
        'avatar',
    )


class SourceDeleteView(DeleteView):
    model = Source
    template_name = 'currency/source_delete.html'
    success_url = reverse_lazy('currency:source-list')

app/currency/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'currency:rate-list' %}">Rates</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'currency:contactus-create' %}">Contact Us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'currency:source-list' %}">Sources</a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">My Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

app/currency/templates/includes/pagination.html
<nav aria-label="">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ pagination_filter }}" tabindex="-1">Previous</a>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if num == page_obj.number %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ page_obj.number }}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}&{{ pagination_filter }}">{{ num }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ pagination_filter }}">Next</a>
            </li>
        {% endif %}
    </ul>
</nav>