app/api/urls.py
from api import views

from django.urls import path

from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from rest_framework import permissions
from rest_framework.routers import DefaultRouter

app_name = 'api'

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


router = DefaultRouter()
router.register('rates', views.RateViewSet,  basename='rate')
router.register('contactus', views.ContactUsViewSet,  basename='contactus')
router.register('sources', views.SourceViewSet, basename='source')

urlpatterns = [path('rates/latest/', views.LatestRatesView.as_view(), name='rates-latest')]

urlpatterns += router.urls

app/currency/urls.py
from currency.views import (
    ContactUsCreateView,
    ContactusListView,

    RateCreateView,
    RateDeleteView,
    RateDetailsView,
    RateListView,
    RateUpdateView,

    SourceCreateView,
    SourceDeleteView,
    SourceDetailsView,
    SourceListView,
    SourceUpdateView,
)

from django.urls import path

app_name = 'currency'


urlpatterns = (
    path('rate/list/', RateListView.as_view(), name='rate-list'),
    path('rate/create/', RateCreateView.as_view(), name='rate-create'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),
    path('rate/details/<int:pk>/', RateDetailsView.as_view(), name='rate-details'),

    path('contactus/list/', ContactusListView.as_view(), name='contactus-list'),
    path('contactus/create/', ContactUsCreateView.as_view(), name='contactus-create'),

    path('source/list/', SourceListView.as_view(), name='source-list'),
    path('source/create/', SourceCreateView.as_view(), name='source-create'),
    path('source/update/<int:pk>/', SourceUpdateView.as_view(), name='source-update'),
    path('source/delete/<int:pk>/', SourceDeleteView.as_view(), name='source-delete'),
    path('source/details/<int:pk>/', SourceDetailsView.as_view(), name='source-details'),
)

app/settings/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import (
    TemplateView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('django.contrib.auth.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
    path('silk/', include('silk.urls', namespace='silk')),

    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('currency/', include('currency.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/currency/models.py
from currency import model_choices as mch

from django.db import models
from django.templatetags.static import static


def avatar_upload_to(instance, filename):
    return f'avatars/{instance.id}/{filename}'


class Rate(models.Model):
    buy = models.DecimalField(max_digits=6, decimal_places=2)
    sale = models.DecimalField(max_digits=6, decimal_places=2)
    created = models.DateField(auto_now_add=True)
    type = models.PositiveSmallIntegerField(  # noqa: A003
        choices=mch.RateTypeChoices.choices,
        default=mch.RateTypeChoices.USD,
    )
    source = models.ForeignKey('currency.Source', on_delete=models.CASCADE)


class ContactUs(models.Model):
    class Meta:
        verbose_name = 'Contact Us'
        verbose_name_plural = 'Contact Us'

    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=128)
    reply_to = models.EmailField()
    subject = models.CharField(max_length=128)
    body = models.CharField(max_length=1024)
    raw_content = models.TextField()


class Source(models.Model):
    source_url = models.CharField(max_length=255)
    name = models.CharField(max_length=64)
    created = models.DateTimeField(auto_now_add=True)
    avatar = models.FileField(
        upload_to=avatar_upload_to,
        default=None,
        null=True,
        blank=True,
    )
    code_name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name

    @property
    def avatar_url(self):
        if self.avatar:
            return self.avatar.url
        return static('images/default-avatar.jpg')


class RequestResponseLog(models.Model):
    path = models.CharField(max_length=255)
    request_method = models.CharField(max_length=255)
    time = models.DecimalField(max_digits=6, decimal_places=4)

# def save(self, *args, **kwargs):
#     if not self.created:
#         self.created = datetime.now()
#     return super().save(*args, **kwargs)

app/currency/forms.py
from currency.models import Rate, Source

from django import forms


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = {
            'buy',
            'sale',
            'type',
            'source',
        }


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = {
            'source_url',
            'name',
        }

app/currency/views.py
from currency.filters import RateFilter
from currency.forms import RateForm, SourceForm
from currency.models import ContactUs, Rate, Source
from currency.tasks import send_email_in_background

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from django_filters.views import FilterView


class RateListView(FilterView):
    paginate_by = 10
    queryset = Rate.objects.all().order_by('-created').select_related('source')
    filterset_class = RateFilter

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['pagination_filter'] = "&".join(
            f"{key}={value}"
            for key, value in self.request.GET.items()
            if key != 'page'
        )
        return context


class RateCreateView(CreateView):
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'currency/rate_create.html'


class RateUpdateView(UserPassesTestMixin, UpdateView):
    form_class = RateForm
    model = Rate
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'currency/rate_update.html'

    def test_func(self):
        return self.request.user.is_superuser


class RateDetailsView(LoginRequiredMixin, DetailView):
    model = Rate


class RateDeleteView(UserPassesTestMixin, DeleteView):
    model = Rate
    template_name = 'currency/rate_delete.html'
    success_url = reverse_lazy('currency:rate-list')

    def test_func(self):
        return self.request.user.is_superuser


class ContactusListView(ListView):
    queryset = ContactUs.objects.all()


class ContactUsCreateView(CreateView):
    model = ContactUs
    template_name = 'currency/contactus_create.html'
    success_url = reverse_lazy('index')
    fields = (
        'name',
        'reply_to',
        'subject',
        'body',
    )

    def form_valid(self, form):
        redirect = super().form_valid(form)
        subject = 'User ContactUs'
        body = f'''
            Request From: {self.object.name}
            Email to reply: {self.object.reply_to}
            Subject: {self.object.subject}
            Body: {self.object.body}
        '''
        send_email_in_background.delay(subject, body)
        # send_email_in_background.apply_async(args=(subject, body))
        '''
        00-8.59 | 9.00-19.00 | 19.01 - 23.59
        9.00    |    send    | 9.00 next day
        '''
        # from datetime import datetime, timedelta
        # eta = datetime(2021, 11, 21, 19, 00, 00)
        # send_email_in_background.apply_async(
        #     kwargs={'subject': subject, 'body': body},
        #     countdown=120,
        # eta=eta,
        # )
        return redirect


class SourceListView(ListView):
    queryset = Source.objects.all().order_by('-created')


class SourceCreateView(CreateView):
    form_class = SourceForm
    success_url = reverse_lazy('currency:source-list')
    template_name = 'currency/source_create.html'


class SourceUpdateView(UpdateView):
    form_class = SourceForm
    model = Source
    success_url = reverse_lazy('currency:source-list')
    template_name = 'currency/source_update.html'


class SourceDetailsView(UpdateView):
    model = Source
    template_name = 'currency/source_detail.html'
    success_url = reverse_lazy('currency:source-list')
    fields = (
        'avatar',
    )


class SourceDeleteView(DeleteView):
    model = Source
    template_name = 'currency/source_delete.html'
    success_url = reverse_lazy('currency:source-list')

app/currency/templates/currency/contactus_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Contact Us{% endblock title %}

{% block content %}
    Contact Us
    <a href="{% url 'currency:contactus-list'%}">List_Contacts</a>

    <form method="post" class="bootstrap4">
        {% csrf_token %}
        <div class="row">
            <div class="col-2">
                {{ form|crispy }}
            </div>
        </div>
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

app/currency/templates/currency/contactus_list.html
{% extends 'base.html' %}

{% block title %}Table{% endblock title %}

{% block content %}
<table border="=1">
    <tr>
        <th>Id</th>
        <th>Reply_to</th>
        <th>Subject</th>
        <th>Name</th>
        <th>Created</th>
    </tr>>
    {% for object in object_list %}
    <tr>
        <td>{{ object.id }}</td>
        <td>{{ object.reply_to }}</td>
        <td>{{ object.subject }}</td>
        <td>{{ object.name }}</td>
        <td>{{ object.created }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock content %}

app/currency/templates/currency/rate_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Create Rate{% endblock title %}

{% block content %}
    Create Rate Form

    <form method="post" class="bootstrap4">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

app/currency/templates/currency/rate_delete.html
{% extends 'base.html' %}

{% block title %}Delete Rate{% endblock title %}

{% block content %}
    Are you sure you want to delete rate with id {{ object.id }}

    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete!</button>
    </form>
{% endblock content %}

app/currency/templates/currency/rate_detail.html
{% extends 'base.html' %}

{% block title %}Rate Detail{% endblock title %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <table class="table table-striped">
            <thead>
            <tr>
                <th>Id</th>>
                <th>Type</th>
                <th>Buy</th>
                <th>Sale</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td> {{ object.id }}</td>
                    <td> {{ object.type }} </td>
                    <td> {{ object.buy }} </td>
                    <td> {{ object.sale }} </td>
                </tr>
            </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

app/currency/templates/currency/rate_filter.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Table{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <a href="{% url 'currency:rate-create' %}">Create Rate</a>
            <br>
            <form method="get" class="bootstrap4">
            <div class="row">
                <div class="col-2">
                {{ filter.form|crispy }}
                <button type="submit">Filter</button>
                </div>
            </div>
            </form>
            <br>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Id</th>>
                <th>Type</th>
                <th>Sale</th>
                <th>Buy</th>
                <th>Source</th>
                <th>Created</th>
                <th colspan="3">Options</th>
            </tr>
            </thead>
            <tbody>
            {% for rate in object_list %}
            <tr>
                <td> {{ rate.id }}</td>
                <td> {{ rate.get_type_display }} </td>
                <td> {{ rate.sale }}</td>
                <td> {{ rate.buy }}</td>
                <td> {{ rate.source.name }} </td>
                <td> {{ rate.created }}</td>

                {% if request.user.is_authenticated %}
                    <td>
                        <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Action
                                </button>
                                {% if request.user.is_superuser %}
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="{% url 'currency:rate-details' rate.id %}">Details</a>
                                    <a class="dropdown-item" href="{% url 'currency:rate-update' rate.id %}">Edit</a>
                                    <a class="dropdown-item" href="{% url 'currency:rate-delete' rate.id %}">Delete</a>
                                    </div>
                                {% else %}
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="{% url 'currency:rate-details' rate.id %}">Details</a>
                                    </div>
                                {% endif %}
                        </div>
                    </td>
                {% else %}
                    <td> <a href="{% url 'login' %}">Login </a> </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            {% include 'includes/pagination.html' %}
        </div>
    </div>

<footer class="text-center text-lg-start bg-light text-muted">
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <div class="container-fluid text-center text-md-left">
      <span>Get connected with us on social networks:</span>
        <a href="instagram.com"><i class="fa fa-instagram"></i></a>
        <a href="twitter.com"><i class="fa fa-twitter"></i></a>
        <a href="linkedin.com"><i class="fa fa-linkedin"></i></a>
        <a href="facebook.com"><i class="fa fa-facebook"></i></a>
    </div>
  </section>
</footer>

{% endblock content %}

app/currency/templates/currency/rate_list.html
{% extends 'base.html' %}

{% block title %}Table{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <a href="{% url 'currency:rate-create' %}">Create Rate</a>
            <br>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Id</th>>
                <th>Type</th>
                <th>Sale</th>
                <th>Buy</th>
                <th>Source</th>
                <th>Created</th>
                <th colspan="3">Options</th>
            </tr>
            </thead>
            <tbody>
            {% for rate in object_list %}
            <tr>
                <td> {{ rate.id }}</td>
                <td> {{ rate.get_type_display }} </td>
                <td> {{ rate.sale }}</td>
                <td> {{ rate.buy }}</td>
                <td> {{ rate.source.name }} </td>
                <td> {{ rate.created }}</td>

                {% if request.user.is_authenticated %}
                    <td>
                        <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Action
                                </button>
                                {% if request.user.is_superuser %}
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="{% url 'currency:rate-details' rate.id %}">Details</a>
                                    <a class="dropdown-item" href="{% url 'currency:rate-update' rate.id %}">Edit</a>
                                    <a class="dropdown-item" href="{% url 'currency:rate-delete' rate.id %}">Delete</a>
                                    </div>
                                {% else %}
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="{% url 'currency:rate-details' rate.id %}">Details</a>
                                    </div>
                                {% endif %}
                        </div>
                    </td>
                {% else %}
                    <td> <a href="{% url 'login' %}">Login </a> </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>
    </div>

<footer class="text-center text-lg-start bg-light text-muted">
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <div class="container-fluid text-center text-md-left">
      <span>Get connected with us on social networks:</span>
        <a href="instagram.com"><i class="fa fa-instagram"></i></a>
        <a href="twitter.com"><i class="fa fa-twitter"></i></a>
        <a href="linkedin.com"><i class="fa fa-linkedin"></i></a>
        <a href="facebook.com"><i class="fa fa-facebook"></i></a>
    </div>
  </section>
</footer>

{% endblock content %}

app/currency/templates/currency/rate_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Rate Update{% endblock title %}

{% block content %}
    Update Rate Form

    <form method="post" class="uniForm">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

app/currency/templates/currency/source_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Source Create{% endblock title %}

{% block content %}
    <form method="post" class="uniForm">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

app/currency/templates/currency/source_delete.html
{% extends 'base.html' %}

{% block title %}Source Delete{% endblock title %}

{% block content %}
    Delete?
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm</button>
    </form>
{% endblock content %}

app/currency/templates/currency/source_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Source Detail{% endblock title %}

{% block content %}
    <img src="{{ object.avatar_url }}" height="150" width="150">
    <br>

    <form method="post" enctype="multipart/form-data" class="bootstrap4">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>

    <div class="row">
        <div class="col-12">
            <table class="table table-striped">
            <thead>
            <tr>
                <th>Name</th>>
                <th>Source_url</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td> {{ object.name }}</td>
                    <td> {{ object.source_url }} </td>
                </tr>
            </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

app/currency/templates/currency/source_list.html
{% extends 'base.html' %}

{% block title %}Table{% endblock title %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <a href="{% url 'currency:source-create' %}">Create Source</a>
            <br>

            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Id</th>>
                    <th>Source_url</th>
                    <th>Name</th>
                    <th>Created</th>
                    <th colspan="3">Options</th>
                </tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object.id }}</td>
                        <td>{{ object.source_url }}</td>
                        <td>{{ object.name }}</td>
                        <td>{{ object.created }}</td>
                        <td>
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Action
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="{% url 'currency:source-update' object.id %}">Edit </a>
                                    <a class="dropdown-item" href="{% url 'currency:source-delete' object.id %}">Delete </a>
                                    <a class="dropdown-item" href="{% url 'currency:source-details' object.id %}">Details </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock content %}

app/currency/templates/currency/source_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Source Update{% endblock title %}

{% block content %}
    Update Source Form

    <form method="post" class="uniForm">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}